# Generated by Django 2.2.6 on 2019-11-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='publish_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
