# Generated by Django 2.2.6 on 2019-11-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191103_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
